//
//  CountryList.swift
//  Project1
//
//  Created by s15 on 22/10/24.
//

struct CountryList{
    struct Country{
        let code:String
        let name:String
    }
    
    static var countryCode: [Country] = [
        Country(code: "ad", name: "Andorra"),
        Country(code: "ae", name: "United Arab Emirates"),
        Country(code: "af", name: "Afghanistan"),
        Country(code: "ag", name: "Antigua and Barbuda"),
        Country(code: "ai", name: "Anguilla"),
        Country(code: "al", name: "Albania"),
        Country(code: "am", name: "Armenia"),
        Country(code: "ao", name: "Angola"),
        Country(code: "aq", name: "Antarctica"),
        Country(code: "ar", name: "Argentina"),
        Country(code: "as", name: "American Samoa"),
        Country(code: "at", name: "Austria"),
        Country(code: "au", name: "Australia"),
        Country(code: "aw", name: "Aruba"),
        Country(code: "ax", name: "Åland Islands"),
        Country(code: "az", name: "Azerbaijan"),
        Country(code: "ba", name: "Bosnia and Herzegovina"),
        Country(code: "bb", name: "Barbados"),
        Country(code: "bd", name: "Bangladesh"),
        Country(code: "be", name: "Belgium"),
        Country(code: "bf", name: "Burkina Faso"),
        Country(code: "bg", name: "Bulgaria"),
        Country(code: "bh", name: "Bahrain"),
        Country(code: "bi", name: "Burundi"),
        Country(code: "bj", name: "Benin"),
        Country(code: "bl", name: "Saint Barthélemy"),
        Country(code: "bm", name: "Bermuda"),
        Country(code: "bn", name: "Brunei"),
        Country(code: "bo", name: "Bolivia"),
        Country(code: "bq", name: "Caribbean Netherlands"),
        Country(code: "br", name: "Brazil"),
        Country(code: "bs", name: "Bahamas"),
        Country(code: "bt", name: "Bhutan"),
        Country(code: "bv", name: "Bouvet Island"),
        Country(code: "bw", name: "Botswana"),
        Country(code: "by", name: "Belarus"),
        Country(code: "bz", name: "Belize"),
        Country(code: "ca", name: "Canada"),
        Country(code: "cc", name: "Cocos (Keeling) Islands"),
        Country(code: "cd", name: "DR Congo"),
        Country(code: "cf", name: "Central African Republic"),
        Country(code: "cg", name: "Republic of the Congo"),
        Country(code: "ch", name: "Switzerland"),
        Country(code: "ci", name: "Côte d'Ivoire (Ivory Coast)"),
        Country(code: "ck", name: "Cook Islands"),
        Country(code: "cl", name: "Chile"),
        Country(code: "cm", name: "Cameroon"),
        Country(code: "cn", name: "China"),
        Country(code: "co", name: "Colombia"),
        Country(code: "cr", name: "Costa Rica"),
        Country(code: "cu", name: "Cuba"),
        Country(code: "cv", name: "Cape Verde"),
        Country(code: "cw", name: "Curaçao"),
        Country(code: "cx", name: "Christmas Island"),
        Country(code: "cy", name: "Cyprus"),
        Country(code: "cz", name: "Czechia"),
        Country(code: "de", name: "Germany"),
        Country(code: "dj", name: "Djibouti"),
        Country(code: "dk", name: "Denmark"),
        Country(code: "dm", name: "Dominica"),
        Country(code: "do", name: "Dominican Republic"),
        Country(code: "dz", name: "Algeria"),
        Country(code: "ec", name: "Ecuador"),
        Country(code: "ee", name: "Estonia"),
        Country(code: "eg", name: "Egypt"),
        Country(code: "eh", name: "Western Sahara"),
        Country(code: "er", name: "Eritrea"),
        Country(code: "es", name: "Spain"),
        Country(code: "et", name: "Ethiopia"),
        Country(code: "eu", name: "European Union"),
        Country(code: "fi", name: "Finland"),
        Country(code: "fj", name: "Fiji"),
        Country(code: "fk", name: "Falkland Islands"),
        Country(code: "fm", name: "Micronesia"),
        Country(code: "fo", name: "Faroe Islands"),
        Country(code: "fr", name: "France"),
        Country(code: "ga", name: "Gabon"),
        Country(code: "gb", name: "United Kingdom"),
        Country(code: "gd", name: "Grenada"),
        Country(code: "ge", name: "Georgia"),
        Country(code: "gf", name: "French Guiana"),
        Country(code: "gg", name: "Guernsey"),
        Country(code: "gh", name: "Ghana"),
        Country(code: "gi", name: "Gibraltar"),
        Country(code: "gl", name: "Greenland"),
        Country(code: "gm", name: "Gambia"),
        Country(code: "gn", name: "Guinea"),
        Country(code: "gp", name: "Guadeloupe"),
        Country(code: "gq", name: "Equatorial Guinea"),
        Country(code: "gr", name: "Greece"),
        Country(code: "gs", name: "South Georgia"),
        Country(code: "gt", name: "Guatemala"),
        Country(code: "gu", name: "Guam"),
        Country(code: "gw", name: "Guinea-Bissau"),
        Country(code: "gy", name: "Guyana"),
        Country(code: "hk", name: "Hong Kong"),
        Country(code: "hm", name: "Heard Island and McDonald Islands"),
        Country(code: "hn", name: "Honduras"),
        Country(code: "hr", name: "Croatia"),
        Country(code: "ht", name: "Haiti"),
        Country(code: "hu", name: "Hungary"),
        Country(code: "id", name: "Indonesia"),
        Country(code: "ie", name: "Ireland"),
        Country(code: "il", name: "Israel"),
        Country(code: "im", name: "Isle of Man"),
        Country(code: "in", name: "India"),
        Country(code: "io", name: "British Indian Ocean Territory"),
        Country(code: "iq", name: "Iraq"),
        Country(code: "ir", name: "Iran"),
        Country(code: "is", name: "Iceland"),
        Country(code: "it", name: "Italy"),
        Country(code: "je", name: "Jersey"),
        Country(code: "jm", name: "Jamaica"),
        Country(code: "jo", name: "Jordan"),
        Country(code: "jp", name: "Japan"),
        Country(code: "ke", name: "Kenya"),
        Country(code: "kg", name: "Kyrgyzstan"),
        Country(code: "kh", name: "Cambodia"),
        Country(code: "ki", name: "Kiribati"),
        Country(code: "km", name: "Comoros"),
        Country(code: "kn", name: "Saint Kitts and Nevis"),
        Country(code: "kp", name: "North Korea"),
        Country(code: "kr", name: "South Korea"),
        Country(code: "kw", name: "Kuwait"),
        Country(code: "ky", name: "Cayman Islands"),
        Country(code: "kz", name: "Kazakhstan"),
        Country(code: "la", name: "Laos"),
        Country(code: "lb", name: "Lebanon"),
        Country(code: "lc", name: "Saint Lucia"),
        Country(code: "li", name: "Liechtenstein"),
        Country(code: "lk", name: "Sri Lanka"),
        Country(code: "lr", name: "Liberia"),
        Country(code: "ls", name: "Lesotho"),
        Country(code: "lt", name: "Lithuania"),
        Country(code: "lu", name: "Luxembourg"),
        Country(code: "lv", name: "Latvia"),
        Country(code: "ly", name: "Libya"),
        Country(code: "ma", name: "Morocco"),
        Country(code: "mc", name: "Monaco"),
        Country(code: "md", name: "Moldova"),
        Country(code: "me", name: "Montenegro"),
        Country(code: "mf", name: "Saint Martin"),
        Country(code: "mg", name: "Madagascar"),
        Country(code: "mh", name: "Marshall Islands"),
        Country(code: "mk", name: "North Macedonia"),
        Country(code: "ml", name: "Mali"),
        Country(code: "mm", name: "Myanmar"),
        Country(code: "mn", name: "Mongolia"),
        Country(code: "mo", name: "Macau"),
        Country(code: "mp", name: "Northern Mariana Islands"),
        Country(code: "mq", name: "Martinique"),
        Country(code: "mr", name: "Mauritania"),
        Country(code: "ms", name: "Montserrat"),
        Country(code: "mt", name: "Malta"),
        Country(code: "mu", name: "Mauritius"),
        Country(code: "mv", name: "Maldives"),
        Country(code: "mw", name: "Malawi"),
        Country(code: "mx", name: "Mexico"),
        Country(code: "my", name: "Malaysia"),
        Country(code: "mz", name: "Mozambique"),
        Country(code: "na", name: "Namibia"),
        Country(code: "nc", name: "New Caledonia"),
        Country(code: "ne", name: "Niger"),
        Country(code: "nf", name: "Norfolk Island"),
        Country(code: "ng", name: "Nigeria"),
        Country(code: "ni", name: "Nicaragua"),
        Country(code: "nl", name: "Netherlands"),
        Country(code: "no", name: "Norway"),
        Country(code: "np", name: "Nepal"),
        Country(code: "nr", name: "Nauru"),
        Country(code: "nu", name: "Niue"),
        Country(code: "nz", name: "New Zealand"),
        Country(code: "om", name: "Oman"),
        Country(code: "pa", name: "Panama"),
        Country(code: "pe", name: "Peru"),
        Country(code: "pf", name: "French Polynesia"),
        Country(code: "pg", name: "Papua New Guinea"),
        Country(code: "ph", name: "Philippines"),
        Country(code: "pk", name: "Pakistan"),
        Country(code: "pl", name: "Poland"),
        Country(code: "pm", name: "Saint Pierre and Miquelon"),
        Country(code: "pn", name: "Pitcairn Islands"),
        Country(code: "pr", name: "Puerto Rico"),
        Country(code: "ps", name: "Palestine"),
        Country(code: "pt", name: "Portugal"),
        Country(code: "pw", name: "Palau"),
        Country(code: "py", name: "Paraguay"),
        Country(code: "qa", name: "Qatar"),
        Country(code: "re", name: "Réunion"),
        Country(code: "ro", name: "Romania"),
        Country(code: "rs", name: "Serbia"),
        Country(code: "ru", name: "Russia"),
        Country(code: "rw", name: "Rwanda"),
        Country(code: "sa", name: "Saudi Arabia"),
        Country(code: "sb", name: "Solomon Islands"),
        Country(code: "sc", name: "Seychelles"),
        Country(code: "sd", name: "Sudan"),
        Country(code: "se", name: "Sweden"),
        Country(code: "sg", name: "Singapore"),
        Country(code: "sh", name: "Saint Helena, Ascension and Tristan da Cunha"),
        Country(code: "si", name: "Slovenia"),
        Country(code: "sj", name: "Svalbard and Jan Mayen"),
        Country(code: "sk", name: "Slovakia"),
        Country(code: "sl", name: "Sierra Leone"),
        Country(code: "sm", name: "San Marino"),
        Country(code: "sn", name: "Senegal"),
        Country(code: "so", name: "Somalia"),
        Country(code: "sr", name: "Suriname"),
        Country(code: "ss", name: "South Sudan"),
        Country(code: "st", name: "São Tomé and Príncipe"),
        Country(code: "sv", name: "El Salvador"),
        Country(code: "sx", name: "Sint Maarten"),
        Country(code: "sy", name: "Syria"),
        Country(code: "sz", name: "Eswatini (Swaziland)"),
        Country(code: "tc", name: "Turks and Caicos Islands"),
        Country(code: "td", name: "Chad"),
        Country(code: "tf", name: "French Southern and Antarctic Lands"),
        Country(code: "tg", name: "Togo"),
        Country(code: "th", name: "Thailand"),
        Country(code: "tj", name: "Tajikistan"),
        Country(code: "tk", name: "Tokelau"),
        Country(code: "tl", name: "Timor-Leste"),
        Country(code: "tm", name: "Turkmenistan"),
        Country(code: "tn", name: "Tunisia"),
        Country(code: "to", name: "Tonga"),
        Country(code: "tr", name: "Turkey"),
        Country(code: "tt", name: "Trinidad and Tobago"),
        Country(code: "tv", name: "Tuvalu"),
        Country(code: "tw", name: "Taiwan"),
        Country(code: "tz", name: "Tanzania"),
        Country(code: "ua", name: "Ukraine"),
        Country(code: "ug", name: "Uganda"),
        Country(code: "um", name: "United States Minor Outlying Islands"),
        Country(code: "un", name: "United Nations"),
        Country(code: "us", name: "United States"),
        Country(code: "uy", name: "Uruguay"),
        Country(code: "uz", name: "Uzbekistan"),
        Country(code: "va", name: "Vatican City (Holy See)"),
        Country(code: "vc", name: "Saint Vincent and the Grenadines"),
        Country(code: "ve", name: "Venezuela"),
        Country(code: "vg", name: "British Virgin Islands"),
        Country(code: "vi", name: "United States Virgin Islands"),
        Country(code: "vn", name: "Vietnam"),
        Country(code: "vu", name: "Vanuatu"),
        Country(code: "wf", name: "Wallis and Futuna"),
        Country(code: "ws", name: "Samoa"),
        Country(code: "xk", name: "Kosovo"),
        Country(code: "ye", name: "Yemen"),
        Country(code: "yt", name: "Mayotte"),
        Country(code: "za", name: "South Africa"),
        Country(code: "zm", name: "Zambia"),
        Country(code: "zw", name: "Zimbabwe")
    ]
}

